@echo off
set PATH=%CD%\local_node\node-v22.21.0-win-x64;%PATH%
echo Starting Ghat Manager Application...
echo Starting Server...
start "Ghat Manager Server" npm run server
echo Starting Client...
start "Ghat Manager Client" npm run client
echo Application started in separate windows.
