import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import sequelize from './mysql.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const sqlFile = path.join(__dirname, 'cleaned_backup_data.sql');

async function restore() {
  try {
    console.log('Reading SQL file...');
    const sqlContent = fs.readFileSync(sqlFile, 'utf-8');

    // Split into statements. 
    // Since my cleaner script outputted well-formed statements ending with ;\n or ;\r\n
    // I can split by ';\n' or similar. 
    // But safely, let's just use the fact that I generated the file myself.
    // The file has TRUNCATE statements and INSERT statements.
    
    // We can enable multipleStatements in a temporary connection or just run them one by one.
    // Running one by one is safer and easier to debug.
    
    // Naive split by ';' might break if text contains ';'. 
    // However, my cleaned_backup_data.sql was generated by taking complete statements from the dump.
    // Let's refine the splitting strategy or just use the existing sequelize connection with a loop.
    
    // Better approach:
    // Read the file. 
    // The file structure I created:
    // SET ...;
    // TRUNCATE ...;
    // ...
    // INSERT ...;
    // ...
    
    // I will read the file and split by `;\n` or `;\r\n` because I wrote it that way.
    // In `prepare_restore.js`: `output += inserts.join('\n');` where each insert ends with `;`.
    // So splitting by `;\n` is likely safe enough for this specific generated file.
    
    const statements = sqlContent.split(/;\s*[\r\n]+/).filter(stmt => stmt.trim().length > 0);

    console.log(`Found ${statements.length} statements to execute.`);
    
    // Authenticate
    await sequelize.authenticate();
    console.log('Database connected.');

    // Execute
    for (const [index, stmt] of statements.entries()) {
      const query = stmt.trim();
      if (!query) continue;
      
      // Append ; back if needed, though sequelize might not need it for single query.
      // But let's keep it clean.
      
      try {
        await sequelize.query(query);
        if ((index + 1) % 100 === 0) {
            console.log(`Executed ${index + 1} statements...`);
        }
      } catch (err) {
        console.error(`Error executing statement #${index + 1}:`);
        console.error(query.substring(0, 100) + '...');
        console.error(err.message);
        // We might want to stop or continue. 
        // For restore, usually stop on error.
        throw err;
      }
    }

    console.log('Restoration completed successfully.');
    process.exit(0);

  } catch (error) {
    console.error('Restoration failed:', error);
    process.exit(1);
  }
}

restore();
